name: Check firmware update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
  push:

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          - model: "SM-G980F"
            region: "AUT"
            codename: "x1slte"
          - model: "SM-G981B"
            region: "AUT"
            codename: "x1sxxx"
          - model: "SM-G985F"
            region: "AUT"
            codename: "y2slte"
          - model: "SM-G986B"
            region: "AUT"
            codename: "y2sxxx"
          - model: "SM-G988B"
            region: "AUT"
            codename: "z3sxxx"
          - model: "SM-N980F"
            region: "DBT"
            codename: "c1sxx"
          - model: "SM-N981B"
            region: "AUT"
            codename: "c1sxxx"
          - model: "SM-N985F"
            region: "XSG"
            codename: "c2sxx"
          - model: "SM-N986B"
            region: "AUT"
            codename: "c2sxxx"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Compare latest version with current version
        id: check
        run: |
          need_update=0
          latest=`curl --retry 5 --retry-delay 5 http://fota-cloud-dn.ospserver.net/firmware/${{ matrix.region }}/${{ matrix.model }}/version.xml | grep latest | sed 's/^[^>]*>//' | sed 's/<.*//'`
          latest_short=`echo $latest | cut -d'/' -f1`
          latest_csc=`echo $latest | cut -d'/' -f2`
          latest_modem=`echo $latest | cut -d'/' -f3`
          current=`cat current.${{ matrix.model }}` || need_update=1
          [[ $latest != $current ]] && need_update=1
          echo "latest_version=$latest" >> $GITHUB_ENV
          echo "latest_shortversion=$latest_short" >> $GITHUB_ENV
          echo "latest_cscversion=$latest_csc" >> $GITHUB_ENV
          echo "latest_modemversion=$latest_modem" >> $GITHUB_ENV
          echo "need_update=$need_update" >> $GITHUB_ENV

      - name: Install dependencies
        if: env.need_update == 1
        run: |
          sudo apt-get update
          sudo apt-get install -y liblz4-tool zip
          sudo wget -O /usr/bin/dtc https://corsica.nu/dtc && sudo chmod +x /usr/bin/dtc
          sudo wget -O /usr/bin/mkdtimg https://corsica.nu/mkdtimg && sudo chmod +x /usr/bin/mkdtimg
          sudo wget -O /usr/bin/splitdt https://corsica.nu/splitdt && sudo chmod +x /usr/bin/splitdt
          sudo wget -O /usr/bin/unpackbootimg https://corsica.nu/unpackbootimg && sudo chmod +x /usr/bin/unpackbootimg
          sudo wget -O /usr/bin/extract-ikconfig https://corsica.nu/extract-ikconfig && sudo chmod +x /usr/bin/extract-ikconfig
          sudo wget -O /usr/bin/samfirm https://github.com/jesec/SamFirm.NET/releases/latest/download/linux-x64 && sudo chmod +x /usr/bin/samfirm

      - name: Fetch firmware
        if: env.need_update == 1
        run: samfirm -m ${{ matrix.model }} -r ${{ matrix.region }}

      - name: Print directory structure
        if: env.need_update == 1
        run: ls -la ${{ matrix.model }}_${{ matrix.region }}

      - name: Get path of files
        if: env.need_update == 1
        id: files
        run: |
          echo "bl=`find -name BL*`" >> $GITHUB_ENV
          echo "ap=`find -name AP*`" >> $GITHUB_ENV
          echo "cp=`find -name CP*`" >> $GITHUB_ENV
          echo "csc=`find -name HOME_CSC*`" >> $GITHUB_ENV

      - name: Check downloaded firmware version
        if: env.need_update == 1
        run: |
          version_short=`echo ${{ env.ap }} | cut -d'_' -f3`
          version_csc=`echo ${{ env.csc }} | cut -d'_' -f5`
          version_modem=`echo ${{ env.cp }} | cut -d'_' -f3`
          changelist=`echo ${{ env.ap }} | cut -d'_' -f5`
          [[ $version_short == ${{ env.latest_shortversion }} ]]
          [[ $version_csc == ${{ env.latest_cscversion }} ]]
          [[ $version_modem == ${{ env.latest_modemversion }} ]]
          echo PDA version: $version_short > versions.txt
          echo CSC version: $version_csc >> versions.txt
          echo Modem version: $version_modem >> versions.txt
          echo Changelist: $changelist >> versions.txt

      - name: Print available disk space
        if: env.need_update == 1
        run: |
          pwd
          sudo df -h
          
      - name: Create zip environment
        if: env.need_update == 1
        run: |
          target_device=`echo ${{ matrix.model }} | cut -d'-' -f2`
          target_version=${{ env.latest_shortversion }}
          mkdir -p $target_version configs tmp
          
      - name: Extract images from AP/BL, dump configs and create zips
        if: env.need_update == 1
        id: releases
        run: |
          target_version=${{ env.latest_shortversion }}
          bls=(harx.bin keystorage.bin ldfw.img sboot.bin ssp.img tzar.img tzsw.img uh.bin up_param.bin dtbo.img modem.bin)
          tar xvf ${{ env.ap }} dtbo.img.lz4 boot.img.lz4 recovery.img.lz4 super.img.lz4
          tar xvf ${{ env.bl }} 
          tar xvf ${{ env.cp }}
          for i in `ls | grep lz4`; do lz4 -dm $i ; rm -rf $i; done
          for i in `ls | grep img`; do echo -n $i " " >> configs/exynos9830-${{ matrix.codename }}_sizes; stat --printf="%s" $i >> configs/exynos9830-${{ matrix.codename }}_sizes; echo "" >> configs/exynos9830-${{ matrix.codename }}_sizes; done
          extract-ikconfig boot.img > configs/exynos9830-${{ matrix.codename }}_defconfig
          rm -rf super.img && cd tmp
          unpackbootimg -i ../boot.img >> ../configs/bootimg.args && mkdtimg dump boot.img-dtb >> ../configs/exynos9830.cfg
          splitdt boot.img-dtb && dtc dtbdump_* -I dtb -O dts -o ../configs/exynos9830.dts && rm -rf *
          mkdtimg dump ../dtbo.img >> ../configs/${{ matrix.codename }}.cfg && splitdt ../dtbo.img
          for i in `ls | grep dtbdump_`; do dtc $i -I dtb -O dts -o $i.txt; done
          for i in `ls | grep txt`;
            do mv $i ../configs/$(cat $i | grep "model =" | sed 's/Samsung //; s/\t//g; s/\"//g; s/model = //; s/\;//' | awk '{print tolower($7"-"$1"_"$2"_"$3"_"$4".dts")}');
          done
          cd ../configs
          zip -r ../$target_version-configs.zip *
          cd ..
          mv boot.img $target_version-stock_boot.img
          mv recovery.img $target_version-stock_recovery.img
          for i in ${bls[@]}; do [[ -e $i ]] && mv $i $target_version/$i; done
          cd $target_version
          tar cvf ../$target_version-odin_flashable.tar *
          cd .. && ls
          echo "tar=`find -name $target_version-odin_flashable.tar`" >> $GITHUB_ENV
          echo "boot=`find -name $target_version-stock_boot.img`" >> $GITHUB_ENV
          echo "recovery=`find -name $target_version-stock_recovery.img`" >> $GITHUB_ENV
          echo "configs=`find -name $target_version-configs.zip`" >> $GITHUB_ENV

      - name: Update current version
        if: env.need_update == 1
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull origin ${{github.ref}} --ff-only
          echo ${{ env.latest_version }} > current.${{ matrix.model }}
          git add current.${{ matrix.model }}
          git commit -m "${{ matrix.model }}: ${{ env.latest_version }}"
          git tag ${{ env.latest_shortversion }}

      - name: Push changes to repo
        if: env.need_update == 1
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.TOKEN }}

      - name: Upload release assets
        if: env.need_update == 1
        uses: CaptainThrowback/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          body_path: versions.txt
          tag_name: ${{ env.latest_shortversion }}
          files: |
            ${{ env.tar }}
            ${{ env.boot }}
            ${{ env.recovery }}
            ${{ env.configs }}
 
